name: Cypress Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Cypress
        run: npx cypress install

      # Configure Cypress to take screenshots for all tests
      - name: Create Cypress config file
        run: |
          echo 'const { defineConfig } = require("cypress");
          module.exports = defineConfig({
            e2e: {
              screenshotOnRunFailure: true,
              screenshotsFolder: "cypress/screenshots",
              trashAssetsBeforeRuns: false // Preserve previous screenshots
            }
          });' > cypress.config.js

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headless: true
          config-file: cypress.config.js # Use our custom config
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      # Upload ALL screenshots (both success and failure)
      - name: Upload All Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: cypress-all-screenshots
          path: cypress/screenshots
          if-no-files-found: warn # Don't fail if no screenshots exist

      # Upload videos separately
      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

